services:
  yolo:
    image: ${IMG_NAME}
    container_name: yolo-dev
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    networks:
      - observability
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector-yolo-dev
    restart: always
    command: ["--config", "/etc/otelcol/config.yaml"]
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
      - /proc:/host_proc:ro
      - /sys:/host_sys:ro
    environment:
      - HOST_PROC=/host_proc
      - HOST_SYS=/host_sys
    networks:
      - observability
    depends_on:
      yolo:
        condition: service_healthy

networks:
  observability:
