name: Deploy YoloService

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH and deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # Save the private key securely
          printf "%s" "$EC2_SSH_KEY" > key.pem
          chmod 400 key.pem

          # Run remote deploy steps via SSH
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            set -e
            cd /home/ubuntu/yoloServiceNEW
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pip install -r torch-requirements.txt
            sudo systemctl restart yolo
            sleep 3
            sudo systemctl status yolo --no-pager
          EOF
