name: Deploy YoloService

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH and deploy
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 400 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << EOF
            cd /home/ubuntu/yoloServiceNEW
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pip install -r torch-requirements.txt
            sudo systemctl restart yolo
          EOF
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
